services:
  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    container_name: ollama
    pull_policy: always
    volumes:
      - ollama_data:/root/.ollama
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:0.1.0
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
volumes:
  postgres:
  ollama_data:
